### ISSUE TITLE
window.fetch is undefined

### ISSUE THREAD

**Issue by Benoit485** [cozy/cozy-client#700]
Hey

When I want use yarn dev from connector, I get this error

`create-cli-client: debug : Starting OAuth flow
(node:21489) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
at OAuthClient._callee$ (/dir/konnectors/boursorama/node_modules/cozy-client/node_modules/cozy-stack-client/dist/CozyStackClient.js:200:130)
at tryCatch (/dir/konnectors/boursorama/node_modules/regenerator-runtime/runtime.js:45:40)
at Generator.invoke [as _invoke] (/dir/konnectors/boursorama/node_modules/regenerator-runtime/runtime.js:274:22)
at Generator.prototype.<computed> [as next] (/dir/konnectors/boursorama/node_modules/regenerator-runtime/runtime.js:97:21)
at asyncGeneratorStep (/dir/konnectors/boursorama/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/dir/konnectors/boursorama/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
at /dir/konnectors/boursorama/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
at new Promise (<anonymous>)
at OAuthClient.<anonymous> (/dir/konnectors/boursorama/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
at OAuthClient.fetch (/dir/konnectors/boursorama/node_modules/cozy-client/node_modules/cozy-stack-client/dist/CozyStackClient.js:233:23)
(node:21489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21489) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.41s.

I look in file 
> `/dir/konnectors/boursorama/node_modules/cozy-client/node_modules/cozy-stack-client/dist/CozyStackClient.js:200:130

Line is :
> fetcher = (0, _xhrFetch.shouldXMLHTTPRequestBeUsed)(method, path, options) ? _xhrFetch.fetchWithXMLHttpRequest : window.fetch;

But I not find object window

Thanks

**Comment by Crash--** [comment]
Thanks for reporting the issue! 

We have released the fix a few days ago (https://github.com/cozy/cozy-client/releases/tag/v13.5.3) 

See https://github.com/konnectors/libs/issues/673 & this PR https://github.com/konnectors/libs/pull/680 

A new version of konnector-lib should be released soon fixing the issue

**Comment by doubleface** [comment]
cozy-jobs-cli@1.13.4 and cozy-konnector-libs@4.34.3 are released

**Comment by ptbrowne** [comment]
I am closing, @Benoit485 please reopen if you keep having the issue. Thanks for reporting the issue.
