### ISSUE TITLE
Invalid JWT token when ACH import

### ISSUE THREAD

**Issue by flohhhh** [cozy/cozy-client#862]
When I execute this command: 
`ACH import test/fixtures/demo.json test/fixtures/helpers/index.js`

I have the following error stack :
```
Importing 14 documents for doctype io.cozy.files...
Unable to handle invalid token error ReferenceError: window is not defined
    at handleInvalidTokenError (/Users/florianpires/Developer/maif-epa-customizations/cozy-banks/node_modules/cozy-ach/node_modules/cozy-client-js/dist/cozy-client.node.js:237:25)
    at /Users/florianpires/Developer/maif-epa-customizations/cozy-banks/node_modules/cozy-ach/node_modules/cozy-client-js/dist/cozy-client.node.js:211:7
    at process._tickCallback (internal/process/next_tick.js:68:7) { [FetchError: {"error":"Invalid JWT token"}]
  name: 'FetchError',
  response:
   Body {
     url: 'http://cozy.tools:8080/files/io.cozy.files.root-dir',
     status: 400,
     statusText: 'Bad Request',
     headers: Headers { _headers: [Object] },
     ok: false,
     body:
      PassThrough {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     bodyUsed: true,
     size: 0,
     timeout: 0,
     _raw:
      [ <Buffer 7b 22 65 72 72 6f 72 22 3a 22 49 6e 76 61 6c 69 64 20 4a 57 54 20 74 6f 6b 65 6e 22 7d 0a> ],
     _abort: false,
     _bytes: 30 },
  url: 'http://cozy.tools:8080/files/io.cozy.files.root-dir',
  status: 400,
  reason: { error: 'Invalid JWT token' } }
Oops! An error occured.
Invalid JWT token
Error: FetchError: {"error":"Invalid JWT token"}
    at importData (/Users/florianpires/Developer/maif-epa-customizations/cozy-banks/node_modules/cozy-ach/libs/importData.js:219:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

to fix this I deleted my token file in `/tmp/.ach-token` and recreated it.

**Comment by ptbrowne** [comment]
Yep, it seems like `window` should not be accessed in node context.

**Comment by ptbrowne** [comment]
Would you be up to take this bug @flohhhh ?

**Comment by flohhhh** [comment]
Yes of course
